# coding: utf-8

"""
    GMO Aozora Net Bank Open API

    <p>Ph2.5向けに作成したもの</p>   # noqa: E501

    OpenAPI spec version: 1.1.10
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from ganb_webhook_client.models.event_type import EventType  # noqa: F401,E501


class SubscribeRequestBody(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'subscribe_status': 'str',
        'event_types': 'list[EventType]'
    }

    attribute_map = {
        'subscribe_status': 'subscribeStatus',
        'event_types': 'eventTypes'
    }

    def __init__(self, subscribe_status=None, event_types=None):  # noqa: E501
        """SubscribeRequestBody - a model defined in Swagger"""  # noqa: E501

        self._subscribe_status = None
        self._event_types = None
        self.discriminator = None

        self.subscribe_status = subscribe_status
        self.event_types = event_types

    @property
    def subscribe_status(self):
        """Gets the subscribe_status of this SubscribeRequestBody.  # noqa: E501

        配信状態 半角数字 0=配信停止要求 1=配信開始要求   # noqa: E501

        :return: The subscribe_status of this SubscribeRequestBody.  # noqa: E501
        :rtype: str
        """
        return self._subscribe_status

    @subscribe_status.setter
    def subscribe_status(self, subscribe_status):
        """Sets the subscribe_status of this SubscribeRequestBody.

        配信状態 半角数字 0=配信停止要求 1=配信開始要求   # noqa: E501

        :param subscribe_status: The subscribe_status of this SubscribeRequestBody.  # noqa: E501
        :type: str
        """
        if subscribe_status is None:
            raise ValueError("Invalid value for `subscribe_status`, must not be `None`")  # noqa: E501
        if subscribe_status is not None and len(subscribe_status) > 1:
            raise ValueError("Invalid value for `subscribe_status`, length must be less than or equal to `1`")  # noqa: E501
        if subscribe_status is not None and len(subscribe_status) < 1:
            raise ValueError("Invalid value for `subscribe_status`, length must be greater than or equal to `1`")  # noqa: E501

        self._subscribe_status = subscribe_status

    @property
    def event_types(self):
        """Gets the event_types of this SubscribeRequestBody.  # noqa: E501

        イベント種別のリスト   # noqa: E501

        :return: The event_types of this SubscribeRequestBody.  # noqa: E501
        :rtype: list[EventType]
        """
        return self._event_types

    @event_types.setter
    def event_types(self, event_types):
        """Sets the event_types of this SubscribeRequestBody.

        イベント種別のリスト   # noqa: E501

        :param event_types: The event_types of this SubscribeRequestBody.  # noqa: E501
        :type: list[EventType]
        """
        if event_types is None:
            raise ValueError("Invalid value for `event_types`, must not be `None`")  # noqa: E501

        self._event_types = event_types

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(SubscribeRequestBody, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, SubscribeRequestBody):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
